# Camera
CAMERA_ID = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
TARGET_FPS = 60

# Hand Tracking
MAX_NUM_HANDS = 2
DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

# Brush
FLOWER_SPACING = 18
MIN_FLOWER_DISTANCE = 16

# Flower
FLOWER_MIN_SCALE = 0.75
FLOWER_MAX_SCALE = 1.25

FLOWER_MIN_ROTATION = -25
FLOWER_MAX_ROTATION = 25

FLOWER_MIN_ALPHA = 180
FLOWER_MAX_ALPHA = 255

# Bloom
BLOOM_DURATION = 1.2

# Particles
MAX_PARTICLES = 800

# Smoothing
SMOOTHING_FACTOR = 0.35